In [1]:
import pandas as pd

In [2]:
def my_function():
    pass

In [3]:
def my_sq(x):
    """Squarea a given value, x
    
    parameters
    ----------
    x: number
    
    returns
    -------
    a squared number
    """
    return x ** 2

In [4]:
my_sq(4)

16

In [5]:
my_sq?

Signature: my_sq(x)
Docstring:
Squarea a given value, x

parameters
----------
x: number

returns
-------
a squared number
File:      c:\users\ahamm\appdata\local\temp\ipykernel_4344\3425176235.py
Type:      function


In [6]:
def avg_2(x, y):
    """calculates the average between 2 number
    """
    return (x + y) / 2

In [7]:
avg_2(10, 20)

15.0

In [8]:
assert avg_2(10, 20) == 15

In [9]:
df = pd.DataFrame({
    'a': [10, 20, 30],
    'b': [20, 30, 40]
})
df

a   b
0  10  20
1  20  30
2  30  40

In [10]:
(df['a'] + df['b']) / 2

0    15.0
1    25.0
2    35.0
dtype: float64

In [11]:
df['a'].apply(my_sq)

0    100
1    400
2    900
Name: a, dtype: int64

In [12]:
def my_exp(x, e):
    """Raise x to the e power
    """
    return x ** e

In [13]:
df['a'].apply(my_exp, e=3)

0     1000
1     8000
2    27000
Name: a, dtype: int64

In [14]:
def print_me(x):
    print(x)

In [15]:
df

a   b
0  10  20
1  20  30
2  30  40

In [16]:
df.apply(print_me)

0    10
1    20
2    30
Name: a, dtype: int64
0    20
1    30
2    40
Name: b, dtype: int64


a    None
b    None
dtype: object

In [17]:
def avg_3(x, y, z):
    return (x + y + z) / 3

In [18]:
def avg_3_apply(col):
    x = col[0]
    y = col[1]
    z = col[2]
    return (x + y + z) / 3

In [19]:
df.apply(avg_3_apply)

a    20.0
b    30.0
dtype: float64

In [20]:
def avg_2_apply(row):
    x = row[0]
    y = row[1]
    return (x + y) / 2
df.apply(avg_2_apply, axis=1)

0    15.0
1    25.0
2    35.0
dtype: float64

In [21]:
import seaborn as sns

In [22]:
titanic = sns.load_dataset('titanic')

In [23]:
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [24]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [25]:
import numpy as np

In [26]:
def count_missing(vec):
    null_vec = pd.isnull(vec)
    null_count = np.sum(null_vec)
    return null_count

In [27]:
titanic.apply(count_missing)

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [28]:
titanic['num_missing'] = titanic.apply(count_missing, axis=1)

In [29]:
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  num_missing  
0    man        True  NaN  Southampton    no  False            1  
1  woman       False    C    Cherbourg   yes  False            0  
2  woman       False  NaN  Southampton   yes   True            1  
3  woman       False    C  Southampton   yes  False            0  
4    man        True  NaN  Southampton    no   True            1

In [30]:
titanic.loc[titanic['num_missing'] > 1]

survived  pclass     sex  age  sibsp  parch     fare embarked   class  \
5           0       3    male  NaN      0      0   8.4583        Q   Third   
17          1       2    male  NaN      0      0  13.0000        S  Second   
19          1       3  female  NaN      0      0   7.2250        C   Third   
26          0       3    male  NaN      0      0   7.2250        C   Third   
28          1       3  female  NaN      0      0   7.8792        Q   Third   
..        ...     ...     ...  ...    ...    ...      ...      ...     ...   
859         0       3    male  NaN      0      0   7.2292        C   Third   
863         0       3  female  NaN      8      2  69.5500        S   Third   
868         0       3    male  NaN      0      0   9.5000        S   Third   
878         0       3    male  NaN      0      0   7.8958        S   Third   
888         0       3  female  NaN      1      2  23.4500        S   Third   

       who  adult_male deck  embark_town alive  alone  num_missing  
5      man        True  NaN   Queenstown    no   True            2  
17     man        True  NaN  Southampton   yes   True            2  
19   woman       False  NaN    Cherbourg   yes   True            2  
26     man        True  NaN    Cherbourg    no   True            2  
28   woman       False  NaN   Queenstown   yes   True            2  
..     ...         ...  ...          ...   ...    ...          ...  
859    man        True  NaN    Cherbourg    no   True            2  
863  woman       False  NaN  Southampton    no  False            2  
868    man        True  NaN  Southampton    no   True            2  
878    man        True  NaN  Southampton    no   True            2  
888  woman       False  NaN  Southampton    no  False            2  

[160 rows x 16 columns]

In [31]:
def avg_2(x, y):
    return (x + y) / 2

In [32]:
avg_2(df['a'], df['b'])

0    15.0
1    25.0
2    35.0
dtype: float64

In [33]:
def avg_2(x, y):
    if (x == 20):
        return np.NaN
    return (x + y) / 2

In [34]:
avg_2(10, 20)

15.0

In [35]:
avg_2(20, 30)

nan

In [36]:
import numpy as np

In [37]:
avg_2_vec = np.vectorize(avg_2)

In [38]:
avg_2_vec(10, 20)

array(15.)

In [39]:
avg_2_vec(df['a'], df['b'])

array([15., nan, 35.])

In [40]:
df

a   b
0  10  20
1  20  30
2  30  40

In [41]:
def avg_2(x, y):
    if (x == 20):
        return np.NaN
    return (x + y) / 2

avg_2_vec = np.vectorize(avg_2)

In [42]:
@np.vectorize
def v_avg_2(x, y):
    if (x == 20):
        return np.NaN
    return (x + y) / 2

In [43]:
v_avg_2(df['a'], df['b'])

array([15., nan, 35.])

In [44]:
import numba

In [45]:
@numba.vectorize
def v_avg_2_numba(x, y):
    if (x == 20):
        return np.NaN
    return (x + y) / 2

In [46]:
v_avg_2_numba(df['a'].values, df['b'].values)

array([15., nan, 35.])

In [47]:
pwd

'F:\\AI\\DEEPLEARNINGALLFILES\\ARTIFICAL INTELEGENTS\\Daniel Chen\\Daniel Chen\\2018-10-python2-master\\notebooks'

In [48]:
ls

 Volume in drive F is ??? ??? ????? ???????
 Volume Serial Number is 4484-8009

 Directory of F:\AI\DEEPLEARNINGALLFILES\ARTIFICAL INTELEGENTS\Daniel Chen\Daniel Chen\2018-10-python2-master\notebooks

03/29/2022  02:45 PM    <DIR>          .
03/29/2022  02:45 PM    <DIR>          ..
10/28/2018  11:21 PM                 0 .gitkeep
03/29/2022  02:43 PM    <DIR>          .ipynb_checkpoints
03/29/2022  02:03 PM            90,914 01-intro.ipynb
03/29/2022  02:04 PM            28,104 02-data_structures.ipynb
03/29/2022  01:59 PM           209,137 03-plots.ipynb
03/29/2022  02:04 PM            56,769 04-combine.ipynb
03/29/2022  02:45 PM            12,593 05-loops.ipynb
03/29/2022  02:45 PM            20,584 06-missing.ipynb
03/29/2022  02:45 PM            40,303 07-apply.ipynb
10/28/2018  11:21 PM            22,676 08-data_types.ipynb
10/28/2018  11:21 PM           131,332 09-tidy.ipynb
10/28/2018  11:21 PM            17,709 10-sql.ipynb
10/28/2018  11:21 PM           106,907 20-facets.ipynb

In [49]:
%%timeit
avg_2_vec(df['a'], df['b'])

31.5 µs ± 3.28 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [50]:
%%timeit
v_avg_2_numba(df['a'].values, df['b'].values)

6.3 µs ± 305 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
